// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package core

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson509cf049DecodeLibCore(in *jlexer.Lexer, out *AccessToken) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "N":
			out.N = int64(in.Uint())
		case "E":
			out.E = int64(in.Uint())
		case "D":
			out.D = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson509cf049EncodeLibCore(out *jwriter.Writer, in AccessToken) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"N\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.N))
	}
	{
		const prefix string = ",\"E\":"
		out.RawString(prefix)
		out.Uint(uint(in.E))
	}
	{
		const prefix string = ",\"D\":"
		out.RawString(prefix)
		out.String(string(in.D))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccessToken) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson509cf049EncodeLibCore(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccessToken) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson509cf049EncodeLibCore(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccessToken) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson509cf049DecodeLibCore(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccessToken) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson509cf049DecodeLibCore(l, v)
}
